# Generated by Django 2.0 on 2018-04-09 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentScan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SourceMaterial',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Source material name')),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Creation date')),
                ('curator', models.CharField(max_length=128, verbose_name='Curator')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transcriptions.SourceMaterial')),
            ],
        ),
        migrations.AddField(
            model_name='documentscan',
            name='transcription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='transcriptions.Transcription'),
        ),
    ]
