# Generated by Django 2.0 on 2018-08-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0002_auto_20180430_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentscan',
            name='scan',
            field=models.FileField(upload_to='document_scans'),
        ),
    ]
