# Generated by Django 2.2.28 on 2022-06-30 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0033_auto_20220530_1000'),
        ('persons', '0016_auto_20220411_1225'),
        ('transcriptions', '0004_historicaldocumentscan_historicalsourcematerial_historicaltranscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltranscription',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical shelf mark of transcribed copy'},
        ),
        migrations.AlterModelOptions(
            name='transcription',
            options={'verbose_name': 'shelf mark of transcribed copy', 'verbose_name_plural': 'shelf mark of transcribed copies'},
        ),
        migrations.CreateModel(
            name='ShelfMark',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shelf_mark', models.CharField(max_length=128, verbose_name='Shelf mark')),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogues.Library')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.Place')),
            ],
        ),
        migrations.AddField(
            model_name='documentscan',
            name='shelf_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcriptions.ShelfMark'),
        ),
        migrations.AddField(
            model_name='historicaldocumentscan',
            name='shelf_mark',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transcriptions.ShelfMark'),
        ),
    ]
