# Generated by Django 2.2.28 on 2022-07-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0005_auto_20220630_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelfmark',
            old_name='shelf_mark',
            new_name='text',
        ),
    ]
