# Generated by Django 2.0 on 2018-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_auto_20180627_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='item_as_listed_in_catalogue',
            field=models.TextField(verbose_name='Full lot description, exactly as in the catalogue'),
        ),
    ]
