# Generated by Django 2.0 on 2018-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_auto_20180713_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['catalogue__year_of_publication', 'catalogue__short_title', 'lot_as_listed_in_catalogue']},
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='item_as_listed_in_catalogue',
            new_name='lot_as_listed_in_catalogue',
        ),
        migrations.AddField(
            model_name='lot',
            name='sales_price',
            field=models.CharField(blank=True, max_length=128, verbose_name='Sales price'),
        ),
    ]
