# Generated by Django 2.0 on 2018-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0004_auto_20180716_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='page_in_catalogue',
            field=models.IntegerField(null=True, verbose_name='Page in catalogue'),
        ),
    ]
