# Generated by Django 2.0 on 2018-08-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0005_lot_page_in_catalogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['index_in_catalogue', 'catalogue__year_of_publication', 'catalogue__short_title', 'lot_as_listed_in_catalogue']},
        ),
        migrations.AddField(
            model_name='lot',
            name='index_in_catalogue',
            field=models.IntegerField(null=True, verbose_name='Index in catalogue'),
        ),
    ]
