# Generated by Django 2.0 on 2018-08-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0006_auto_20180808_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['catalogue__year_of_publication', 'catalogue__short_title', 'index_in_catalogue', 'lot_as_listed_in_catalogue']},
        ),
    ]
