# Generated by Django 2.0 on 2018-09-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0010_auto_20180924_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='bookseller_category_books',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='bookseller_category_non_books',
        ),
        migrations.AddField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogues.Category'),
        ),
    ]
