# Generated by Django 2.0.13 on 2019-03-25 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0009_auto_20190325_0918'),
        ('catalogues', '0012_auto_20190225_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='CataloguePublicationPlace',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Catalogue')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Place')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCataloguePublicationPlace',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('catalogue', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogues.Catalogue')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persons.Place')),
            ],
            options={
                'verbose_name': 'historical catalogue publication place',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
