# Generated by Django 2.0.13 on 2019-03-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0013_cataloguepublicationplace_historicalcataloguepublicationplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parisiancategory',
            options={'verbose_name_plural': 'parisian categories'},
        ),
        migrations.AlterField(
            model_name='cataloguepublicationplace',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_places', to='catalogues.Catalogue'),
        ),
        migrations.AlterField(
            model_name='cataloguepublicationplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_catalogues', to='persons.Place'),
        ),
    ]
