# Generated by Django 2.0.13 on 2019-07-01 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0014_auto_20190325_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CataloguePlaceRelationType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cataloguepublicationplace',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogues.CataloguePlaceRelationType'),
        ),
        migrations.AddField(
            model_name='historicalcataloguepublicationplace',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogues.CataloguePlaceRelationType'),
        ),
    ]
