# Generated by Django 2.0.13 on 2019-07-01 08:12

from django.db import migrations


def add_publication_type(apps, schema_editor):
    """
    Adds 'publication' to the CataloguePublicationRelationType 
    and uses this as default for all existing CataloguePublicatioinRelations    
    :param apps: 
    :param schema_editor: 
    :return: 
    """
    CataloguePlaceRelationType = apps.get_model('catalogues', 'CataloguePlaceRelationType')
    publication_type = CataloguePlaceRelationType(name='publication')
    publication_type.save()

    CataloguePlaceRelation = apps.get_model('catalogues', 'CataloguePlaceRelation')
    for relation in CataloguePlaceRelation.objects.all():
        relation.type = publication_type
        relation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0016_auto_20190701_0804'),
    ]

    operations = [
        migrations.RunPython(add_publication_type),
    ]
