# Generated by Django 2.0.13 on 2019-07-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0017_auto_20190701_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueplacerelation',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_places', to='catalogues.Catalogue'),
        ),
        migrations.AlterField(
            model_name='catalogueplacerelation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_catalogues', to='persons.Place'),
        ),
    ]
