# Generated by Django 2.0.13 on 2020-06-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0018_auto_20190701_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={},
        ),
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogues.Category'),
        ),
    ]
