# Generated by Django 2.2.13 on 2021-04-21 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0019_auto_20200604_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogues.Dataset'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='dataset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogues.Dataset'),
        ),
    ]
