# Generated by Django 2.2.13 on 2021-04-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0021_auto_20210421_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.Dataset'),
        ),
    ]
