# Generated by Django 2.2.27 on 2022-04-11 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_auto_20220411_1225'),
        ('persons', '0016_auto_20220411_1225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogues', '0023_historicaldataset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Collection_TMP',
        ),
        migrations.RenameModel(
            old_name='CollectionYear',
            new_name='Collection_TMPYear',
        ),
        migrations.RenameModel(
            old_name='HistoricalCollection',
            new_name='HistoricalCollection_TMP',
        ),
        migrations.RenameModel(
            old_name='HistoricalCollectionYear',
            new_name='HistoricalCollection_TMPYear',
        ),
        migrations.RenameModel(
            old_name='HistoricalPersonCollectionRelation',
            new_name='HistoricalPersonCollection_TMPRelation',
        ),
        migrations.RenameModel(
            old_name='PersonCollectionRelation',
            new_name='PersonCollection_TMPRelation',
        ),
        migrations.AlterModelOptions(
            name='historicalcollection_tmp',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical collection_tmp'},
        ),
        migrations.AlterModelOptions(
            name='historicalcollection_tmpyear',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical collection_tmp year'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersoncollection_tmprelation',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical person collection_tmp relation'},
        ),
        migrations.RenameField(
            model_name='catalogue',
            old_name='collection',
            new_name='collection_TMP',
        ),
        migrations.RenameField(
            model_name='collection_tmpyear',
            old_name='collection',
            new_name='collection_TMP',
        ),
        migrations.RenameField(
            model_name='historicalcatalogue',
            old_name='collection',
            new_name='collection_TMP',
        ),
        migrations.RenameField(
            model_name='historicalcollection_tmpyear',
            old_name='collection',
            new_name='collection_TMP',
        ),
        migrations.RenameField(
            model_name='historicalpersoncollection_tmprelation',
            old_name='collection',
            new_name='collection_TMP',
        ),
        migrations.RenameField(
            model_name='personcollection_tmprelation',
            old_name='collection',
            new_name='collection_TMP',
        ),
        migrations.AlterUniqueTogether(
            name='personcollection_tmprelation',
            unique_together={('person', 'collection_TMP')},
        ),
    ]
