# Generated by Django 2.2.27 on 2022-04-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0016_auto_20220411_1225'),
        ('catalogues', '0024_auto_20220411_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='collection_TMP',
            new_name='collection_tmp',
        ),
        migrations.RenameField(
            model_name='collection_tmpyear',
            old_name='collection_TMP',
            new_name='collection_tmp',
        ),
        migrations.RenameField(
            model_name='historicalcatalogue',
            old_name='collection_TMP',
            new_name='collection_tmp',
        ),
        migrations.RenameField(
            model_name='historicalcollection_tmpyear',
            old_name='collection_TMP',
            new_name='collection_tmp',
        ),
        migrations.RenameField(
            model_name='historicalpersoncollection_tmprelation',
            old_name='collection_TMP',
            new_name='collection_tmp',
        ),
        migrations.RenameField(
            model_name='personcollection_tmprelation',
            old_name='collection_TMP',
            new_name='collection_tmp',
        ),
        migrations.AlterUniqueTogether(
            name='personcollection_tmprelation',
            unique_together={('person', 'collection_tmp')},
        ),
    ]
