# Generated by Django 2.2.27 on 2022-04-13 08:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0016_auto_20220411_1225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcriptions', '0004_historicaldocumentscan_historicalsourcematerial_historicaltranscription'),
        ('catalogues', '0025_auto_20220412_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalogue',
            new_name='Collection',
        ),
        migrations.RenameModel(
            old_name='CatalogueCatalogueTypeRelation',
            new_name='CollectionCollectionTypeRelation',
        ),
        migrations.RenameModel(
            old_name='CatalogueHeldBy',
            new_name='CollectionHeldBy',
        ),
        migrations.RenameModel(
            old_name='CataloguePlaceRelation',
            new_name='CollectionPlaceRelation',
        ),
        migrations.RenameModel(
            old_name='CataloguePlaceRelationType',
            new_name='CollectionPlaceRelationType',
        ),
        migrations.RenameModel(
            old_name='CatalogueType',
            new_name='CollectionType',
        ),
        migrations.RenameModel(
            old_name='HistoricalCatalogue',
            new_name='HistoricalCollection',
        ),
        migrations.RenameModel(
            old_name='HistoricalCatalogueCatalogueTypeRelation',
            new_name='HistoricalCollectionCollectionTypeRelation',
        ),
        migrations.RenameModel(
            old_name='HistoricalCatalogueHeldBy',
            new_name='HistoricalCollectionHeldBy',
        ),
        migrations.RenameModel(
            old_name='HistoricalCataloguePlaceRelation',
            new_name='HistoricalCollectionPlaceRelation',
        ),
        migrations.RenameModel(
            old_name='HistoricalCatalogueType',
            new_name='HistoricalCollectionType',
        ),
        migrations.RenameModel(
            old_name='HistoricalPersonCatalogueRelation',
            new_name='HistoricalPersonCollectionRelation',
        ),
        migrations.RenameModel(
            old_name='HistoricalPersonCatalogueRelationRole',
            new_name='HistoricalPersonCollectionRelationRole',
        ),
        migrations.RenameModel(
            old_name='PersonCatalogueRelation',
            new_name='PersonCollectionRelation',
        ),
        migrations.RenameModel(
            old_name='PersonCatalogueRelationRole',
            new_name='PersonCollectionRelationRole',
        ),
        migrations.AlterModelOptions(
            name='historicalcollection',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical collection'},
        ),
        migrations.AlterModelOptions(
            name='historicalcollectioncollectiontyperelation',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical collection collection type relation'},
        ),
        migrations.AlterModelOptions(
            name='historicalcollectionheldby',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical collection held by'},
        ),
        migrations.AlterModelOptions(
            name='historicalcollectionplacerelation',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical collection place relation'},
        ),
        migrations.AlterModelOptions(
            name='historicalcollectiontype',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical collection type'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersoncollectionrelation',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical person collection relation'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersoncollectionrelationrole',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical person collection relation role'},
        ),
    ]
