# Generated by Django 2.2.27 on 2022-04-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0026_auto_20220413_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='collectioncollectiontyperelation',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='collectionheldby',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='collectionplacerelation',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='historicalcategory',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='historicalcollectioncollectiontyperelation',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='historicalcollectionheldby',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='historicalcollectionplacerelation',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='historicallot',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='historicallot',
            old_name='index_in_catalogue',
            new_name='index_in_collection',
        ),
        migrations.RenameField(
            model_name='historicallot',
            old_name='lot_as_listed_in_catalogue',
            new_name='lot_as_listed_in_collection',
        ),
        migrations.RenameField(
            model_name='historicallot',
            old_name='number_in_catalogue',
            new_name='number_in_collection',
        ),
        migrations.RenameField(
            model_name='historicallot',
            old_name='page_in_catalogue',
            new_name='page_in_collection',
        ),
        migrations.RenameField(
            model_name='historicalpersoncollectionrelation',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='index_in_catalogue',
            new_name='index_in_collection',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='lot_as_listed_in_catalogue',
            new_name='lot_as_listed_in_collection',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='number_in_catalogue',
            new_name='number_in_collection',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='page_in_catalogue',
            new_name='page_in_collection',
        ),
        migrations.RenameField(
            model_name='personcollectionrelation',
            old_name='catalogue',
            new_name='collection',
        ),
        migrations.AlterUniqueTogether(
            name='collectioncollectiontyperelation',
            unique_together={('collection', 'type')},
        ),
    ]
