# Generated by Django 2.2.27 on 2022-04-14 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0027_auto_20220412_1103'),
        ('persons', '0016_auto_20220411_1225'),
        ('catalogues', '0027_auto_20220413_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection_TMP',
            new_name='Catalogue',
        ),
        migrations.RenameModel(
            old_name='Collection_TMPYear',
            new_name='CatalogueYear',
        ),
        migrations.RenameModel(
            old_name='HistoricalCollection_TMP',
            new_name='HistoricalCatalogue',
        ),
        migrations.RenameModel(
            old_name='HistoricalCollection_TMPYear',
            new_name='HistoricalCatalogueYear',
        ),
        migrations.RenameModel(
            old_name='HistoricalPersonCollection_TMPRelation',
            new_name='HistoricalPersonCatalogueRelation',
        ),
        migrations.RenameModel(
            old_name='PersonCollection_TMPRelation',
            new_name='PersonCatalogueRelation',
        ),
        migrations.AlterModelOptions(
            name='historicalcatalogue',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical catalogue'},
        ),
        migrations.AlterModelOptions(
            name='historicalcatalogueyear',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical catalogue year'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersoncataloguerelation',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical person catalogue relation'},
        ),
        migrations.RenameField(
            model_name='catalogueyear',
            old_name='collection_tmp',
            new_name='catalogue',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='collection_tmp',
            new_name='catalogue',
        ),
        migrations.RenameField(
            model_name='historicalcatalogueyear',
            old_name='collection_tmp',
            new_name='catalogue',
        ),
        migrations.RenameField(
            model_name='historicalcollection',
            old_name='collection_tmp',
            new_name='catalogue',
        ),
        migrations.RenameField(
            model_name='historicalpersoncataloguerelation',
            old_name='collection_tmp',
            new_name='catalogue',
        ),
        migrations.RenameField(
            model_name='personcataloguerelation',
            old_name='collection_tmp',
            new_name='catalogue',
        ),
        migrations.AlterField(
            model_name='collectionplacerelation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_collections', to='persons.Place'),
        ),
        migrations.AlterField(
            model_name='collectiontype',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Name of the collection type'),
        ),
        migrations.AlterField(
            model_name='historicalcollectiontype',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Name of the collection type'),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='index_in_collection',
            field=models.IntegerField(null=True, verbose_name='Index in collection'),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='lot_as_listed_in_collection',
            field=models.TextField(verbose_name='Full lot description, exactly as in the collection'),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='number_in_collection',
            field=models.CharField(max_length=128, verbose_name='Number in collection'),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='page_in_collection',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page in collection'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncollectionrelationrole',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Role name for a person-collection relation'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='index_in_collection',
            field=models.IntegerField(null=True, verbose_name='Index in collection'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_as_listed_in_collection',
            field=models.TextField(verbose_name='Full lot description, exactly as in the collection'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='number_in_collection',
            field=models.CharField(max_length=128, verbose_name='Number in collection'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='page_in_collection',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page in collection'),
        ),
        migrations.AlterField(
            model_name='personcollectionrelationrole',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Role name for a person-collection relation'),
        ),
        migrations.AlterUniqueTogether(
            name='personcataloguerelation',
            unique_together={('person', 'catalogue')},
        ),
    ]
