# Generated by Django 2.2.28 on 2022-05-30 09:51

from django.db import migrations


def copy_catalogue_collection_relation(apps, schema_editor):
    """
    Add the catalogue foreign key to the catalogue_m2m relation
    :param apps:
    :param schema_editor:
    :return:
    """
    Collection = apps.get_model('catalogues', 'Collection')
    for collection in Collection.objects.filter(catalogue__isnull=False):
        collection.catalogue_m2m.add(collection.catalogue)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0029_auto_20220530_0950'),
    ]

    operations = [
        migrations.RunPython(copy_catalogue_collection_relation)
    ]
