# Generated by Django 2.2.28 on 2022-05-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0031_auto_20220530_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='catalogue_m2m',
            new_name='catalogue',
        ),
    ]
