# Generated by Django 2.2.28 on 2022-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0032_auto_20220530_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='catalogue',
            field=models.ManyToManyField(related_name='collection', through='catalogues.CatalogueCollectionRelation', to='catalogues.Catalogue'),
        ),
    ]
