# Generated by Django 2.2.28 on 2022-06-30 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0005_auto_20220630_0832'),
        ('catalogues', '0033_auto_20220530_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='shelf_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcriptions.ShelfMark'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='shelf_mark',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transcriptions.ShelfMark'),
        ),
    ]
