# Generated by Django 4.1.2 on 2022-11-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogues", "0034_auto_20220630_0832"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcatalogue",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical catalogue",
                "verbose_name_plural": "historical catalogues",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcatalogueyear",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical catalogue year",
                "verbose_name_plural": "historical catalogue years",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical category",
                "verbose_name_plural": "historical categories",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcollection",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical collection",
                "verbose_name_plural": "historical collections",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcollectioncollectiontyperelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical collection collection type relation",
                "verbose_name_plural": "historical collection collection type relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcollectionheldby",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical collection held by",
                "verbose_name_plural": "historical collection held bys",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcollectionplacerelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical collection place relation",
                "verbose_name_plural": "historical collection place relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcollectiontype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical collection type",
                "verbose_name_plural": "historical collection types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldataset",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical dataset",
                "verbose_name_plural": "historical datasets",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallibrary",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical library",
                "verbose_name_plural": "historical libraries",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallot",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical lot",
                "verbose_name_plural": "historical lots",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalparisiancategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical parisian category",
                "verbose_name_plural": "historical parisian categories",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpersoncataloguerelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person catalogue relation",
                "verbose_name_plural": "historical person catalogue relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpersoncollectionrelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person collection relation",
                "verbose_name_plural": "historical person collection relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpersoncollectionrelationrole",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person collection relation role",
                "verbose_name_plural": "historical person collection relation roles",
            },
        ),
        migrations.AlterField(
            model_name="historicalcatalogue",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcatalogueyear",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcategory",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcollection",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcollectioncollectiontyperelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcollectionheldby",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcollectionplacerelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcollectiontype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldataset",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicallibrary",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicallot",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalparisiancategory",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpersoncataloguerelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpersoncollectionrelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpersoncollectionrelationrole",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
