# Generated by Django 4.1.2 on 2023-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogues", "0035_alter_historicalcatalogue_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="year_of_publication_end",
            field=models.IntegerField(
                null=True, verbose_name="Year of publication: end of range"
            ),
        ),
        migrations.AddField(
            model_name="historicalcollection",
            name="year_of_publication_end",
            field=models.IntegerField(
                null=True, verbose_name="Year of publication: end of range"
            ),
        ),
    ]
