# Generated by Django 4.1.2 on 2023-01-26 13:01

from django.db import migrations, models
import django.db.models.deletion


def copy_shelf_mark_from_collection_to_catalogue(apps, schema_editor):
    """
    Copy the contents of the shelf_mark field of Collection
    to the (new) shelf_mark field of Catalogue
    :param apps:
    :param schema_editor:
    :return:
    """
    Collection = apps.get_model('catalogues', 'Collection')
    Catalogue = apps.get_model('catalogues', 'Catalogue')

    # Find the catalogues that have more than one Collection that have non-empty 'shelf_mark's
    catalogues = Catalogue.objects.annotate(
        shelfmark_count=models.Count('collection', filter=models.Q(collection__shelf_mark__isnull=False))).filter(
        shelfmark_count__gt=1)

    # Of those catalogues, see if one of them have different Collection.shelf_mark values
    catalogues_with_different_shelf_marks = [
        catalogue for catalogue in catalogues
        if len(set(Collection.objects.filter(catalogue=catalogue).values_list('shelf_mark__text'))) > 1
    ]

    if catalogues_with_different_shelf_marks:
        raise Exception("The following catalogues do not have a single associated shelf mark:",
                        ", ".join(catalogues_with_different_shelf_marks))


    # Go ahead and copy shelf_marks
    for catalogue in Catalogue.objects.all():
        collection_with_non_empty_shelf_mark = catalogue.collection.filter(shelf_mark__isnull=False).first()
        if collection_with_non_empty_shelf_mark:
            catalogue.shelf_mark = collection_with_non_empty_shelf_mark.shelf_mark
            catalogue.save()


class Migration(migrations.Migration):

    dependencies = [
        ("transcriptions", "0009_alter_historicaldocumentscan_options_and_more"),
        ("catalogues", "0036_add_year_of_publication_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogue",
            name="shelf_mark",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transcriptions.shelfmark",
            ),
        ),
        migrations.AddField(
            model_name="historicalcatalogue",
            name="shelf_mark",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="transcriptions.shelfmark",
            ),
        ),
        migrations.RunPython(copy_shelf_mark_from_collection_to_catalogue),
        migrations.RemoveField(
            model_name='collection',
            name='shelf_mark',
        ),
        migrations.RemoveField(
            model_name='historicalcollection',
            name='shelf_mark',
        ),
    ]
