# Generated by Django 4.1.2 on 2022-11-29 10:31

from django.db import migrations, models


def copy_full_title_from_collection_to_catalogue(apps, schema_editor):
    """
    Copy the contents of the full_title field of Collection
    to the (new) full_title field of Catalogue
    :param apps:
    :param schema_editor:
    :return:
    """
    Collection = apps.get_model('catalogues', 'Collection')
    Catalogue = apps.get_model('catalogues', 'Catalogue')
    for collection in Collection.objects.all():
        Catalogue.objects.filter(collection=collection).update(full_title=collection.full_title)


class Migration(migrations.Migration):

    dependencies = [
        ("catalogues", "0037_catalogue_shelf_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogue",
            name="full_title",
            field=models.TextField(null=True, verbose_name="Full title"),
        ),
        migrations.AddField(
            model_name="historicalcatalogue",
            name="full_title",
            field=models.TextField(null=True, verbose_name="Full title"),
        ),

        migrations.RunPython(copy_full_title_from_collection_to_catalogue)
    ]
