# Generated by Django 4.2.15 on 2025-01-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0009_alter_historicaldocumentscan_options_and_more'),
        ('catalogues', '0038_alter_collection_year_of_publication_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='shelf_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcriptions.shelfmark'),
        ),
    ]
