# Generated by Django 4.2.20 on 2025-04-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0039_alter_catalogue_shelf_mark'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['year_of_publication'], name='year_of_publication_idx'),
        ),
    ]
