# Generated by Django 4.2.26 on 2026-02-26 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0022_person_earliest_edition_year_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogues', '0039_alter_catalogue_shelf_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCollectionPublicationPlace',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('collection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogues.collection')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persons.place')),
            ],
            options={
                'verbose_name': 'historical collection publication place',
                'verbose_name_plural': 'historical collection publication places',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CollectionPublicationPlace',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_places', to='catalogues.collection')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_collections', to='persons.place')),
            ],
            options={
                'unique_together': {('place', 'collection')},
            },
        ),
    ]
