# Generated by Django 4.2.26 on 2026-02-25 13:54

from django.db import migrations


TYPE_NAME = 'publication'


def move_collection_publication_place(apps, schema_editor):
    CollectionPublicationPlace = apps.get_model('catalogues', 'CollectionPublicationPlace')
    CollectionPlaceRelation = apps.get_model('catalogues', 'CollectionPlaceRelation')
    CollectionPlaceRelationType = apps.get_model('catalogues', 'CollectionPlaceRelationType')

    for collection_place_relation in CollectionPlaceRelation.objects.filter(type__name=TYPE_NAME):
        CollectionPublicationPlace.objects.create(
            uuid=collection_place_relation.uuid,
            place=collection_place_relation.place,
            collection=collection_place_relation.collection,
        )
        collection_place_relation.delete()

    CollectionPlaceRelationType.objects.filter(name=TYPE_NAME).delete()


def return_collection_publication_place(apps, schema_editor):
    CollectionPublicationPlace = apps.get_model('catalogues', 'CollectionPublicationPlace')
    CollectionPlaceRelation = apps.get_model('catalogues', 'CollectionPlaceRelation')
    CollectionPlaceRelationType = apps.get_model('catalogues', 'CollectionPlaceRelationType')

    publication_type, created = CollectionPlaceRelationType.objects.get_or_create(name=TYPE_NAME)

    for collection_publication_place in CollectionPublicationPlace.objects.all():
        CollectionPlaceRelation.objects.create(
            uuid=collection_publication_place.uuid,
            collection=collection_publication_place.collection,
            place=collection_publication_place.place,
            type=publication_type,
        )
        collection_publication_place.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0040_historicalcollectionpublicationplace_and_more'),
    ]

    operations = [
        migrations.RunPython(move_collection_publication_place, reverse_code=return_collection_publication_place),
    ]
