# Generated by Django 2.0 on 2018-04-09 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFormat',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Format name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_title', models.CharField(max_length=128, null=True, verbose_name='Short title')),
                ('number_of_volumes', models.CharField(max_length=128, verbose_name='Number of volumes, as listed in the catalogue')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Collection')),
                ('lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogues.Lot')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAuthor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='persons.Person')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBookFormatRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.BookFormat')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_formats', to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemItemTypeRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLanguageRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterialDetailsRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Name of the item type')),
            ],
        ),
        migrations.CreateModel(
            name='ItemWorkRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('language_code_2char', models.CharField(help_text='Language code (2 characters long) of a written language. This also includes codes of the form zh-Hans, cf. IETF BCP 47', max_length=7, unique=True)),
                ('language_code_3char', models.CharField(help_text='ISO 639-3 language code (3 characters long) of a written language.', max_length=3, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128, null=True, verbose_name='Binding material details description')),
            ],
        ),
        migrations.CreateModel(
            name='PersonItemRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonItemRelationRole',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Role name for a person-item relation')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Year of publication')),
                ('year_tag', models.CharField(max_length=128, verbose_name='Year of publication tag')),
                ('terminus_post_quem', models.BooleanField(default=False, verbose_name='Terminus post quem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='items.Item')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Publication')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='The text of the class')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Title of a work')),
                ('viaf_id', models.CharField(max_length=32, verbose_name='VIAF ID of a work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAuthor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='persons.Person')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='items.Work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSubject',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Subject')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Work')),
            ],
        ),
        migrations.AddField(
            model_name='personitemrelation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.PersonItemRelationRole'),
        ),
        migrations.AddField(
            model_name='itemworkrelation',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.Work'),
        ),
        migrations.AddField(
            model_name='itemmaterialdetailsrelation',
            name='material_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.MaterialDetails'),
        ),
        migrations.AddField(
            model_name='itemlanguagerelation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.Language'),
        ),
        migrations.AddField(
            model_name='itemitemtyperelation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemType'),
        ),
        migrations.AlterUniqueTogether(
            name='workauthor',
            unique_together={('work', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('publisher', 'publication')},
        ),
        migrations.AlterUniqueTogether(
            name='itemworkrelation',
            unique_together={('item', 'work')},
        ),
        migrations.AlterUniqueTogether(
            name='itemmaterialdetailsrelation',
            unique_together={('item', 'material_details')},
        ),
        migrations.AlterUniqueTogether(
            name='itemlanguagerelation',
            unique_together={('item', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='itemitemtyperelation',
            unique_together={('item', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='itembookformatrelation',
            unique_together={('item', 'book_format')},
        ),
        migrations.AlterUniqueTogether(
            name='itemauthor',
            unique_together={('item', 'author')},
        ),
    ]
