# Generated by Django 2.0.1 on 2018-01-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='date_of_publication',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='date_of_publication_tag',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='short_title',
            field=models.CharField(max_length=128, null=True, verbose_name='Short title'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='year_of_publication_end',
            field=models.IntegerField(null=True, verbose_name='Year of publication (end of interval)'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='year_of_publication_start',
            field=models.IntegerField(null=True, verbose_name='Year of publication (start of interval)'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='year_of_publication_text',
            field=models.CharField(max_length=128, null=True, verbose_name='Year of publication text'),
        ),
        migrations.AlterField(
            model_name='bindingmaterialdetails',
            name='text',
            field=models.CharField(max_length=128, null=True, verbose_name='Binding material details text'),
        ),
        migrations.AlterField(
            model_name='bookformat',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Format name'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='bibliography',
            field=models.TextField(null=True, verbose_name='Bibliography'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='full_title',
            field=models.TextField(null=True, verbose_name='Full title'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='notes',
            field=models.TextField(null=True, verbose_name='Notes for the Mediate project'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='preface_and_paratexts',
            field=models.TextField(null=True, verbose_name='Preface or prefatory / concluding text'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.CatalogueType'),
        ),
        migrations.AlterField(
            model_name='cataloguetype',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Name of the catalogue type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='viaf_id',
            field=models.CharField(max_length=128, null=True, verbose_name='VIAF ID (https://viaf.org)'),
        ),
        migrations.AlterField(
            model_name='personbookitemrelationtype',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Type of person-book item relation'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Name of the place'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Publisher name'),
        ),
    ]
