# Generated by Django 2.0 on 2018-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180509_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='viaf_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='VIAF ID of a work'),
        ),
    ]
