# Generated by Django 2.0.1 on 2018-01-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180129_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='catalogue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Catalogue'),
        ),
    ]
