# Generated by Django 2.0 on 2018-07-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180530_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['lot__catalogue__year_of_publication', 'lot__catalogue__short_title', 'lot__item_as_listed_in_catalogue']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='work',
            name='viaf_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='VIAF ID of a work'),
        ),
    ]
