# Generated by Django 2.0.1 on 2018-02-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20180131_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='year_of_publication_end',
            new_name='terminus_post_quem',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='year_of_publication_text',
        ),
    ]
