# Generated by Django 2.0 on 2018-07-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20180703_0731'),
        ('items', '0005_auto_20180713_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='publication',
            new_name='manifestation',
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifestations', to='items.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('publisher', 'manifestation')},
        ),
    ]
