# Generated by Django 2.0.1 on 2018-02-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20180205_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='terminus_post_quem',
            field=models.IntegerField(null=True, verbose_name='Terminus post quem'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='year_of_publication',
            field=models.IntegerField(null=True, verbose_name='Year of publication'),
        ),
    ]
