# Generated by Django 2.0.1 on 2018-02-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20180205_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItemYearIntervalRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.BookItem')),
            ],
        ),
        migrations.CreateModel(
            name='YearInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(verbose_name='Start year of interval')),
                ('end_year', models.IntegerField(verbose_name='End year of inter')),
            ],
        ),
        migrations.AddField(
            model_name='bookitemyearintervalrelation',
            name='year_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.YearInterval'),
        ),
        migrations.AlterUniqueTogether(
            name='bookitemyearintervalrelation',
            unique_together={('book_item', 'year_interval')},
        ),
    ]
