# Generated by Django 2.0 on 2018-07-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20180713_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['lot__catalogue__year_of_publication', 'lot__catalogue__short_title', 'lot__lot_as_listed_in_catalogue']},
        ),
    ]
