# Generated by Django 2.0 on 2018-07-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20180716_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='persons.Place'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Year of publication'),
        ),
    ]
