# Generated by Django 2.0.1 on 2018-02-05 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20180205_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
