# Generated by Django 2.0 on 2018-09-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20180716_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBookFormatRelation',
        ),
        migrations.AddField(
            model_name='item',
            name='book_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.BookFormat'),
        ),
    ]
