# Generated by Django 2.0 on 2018-02-15 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20180205_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name of the source')),
                ('description', models.TextField(verbose_name='Description of the source')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Place')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCollectionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Collection')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Person')),
            ],
        ),
        migrations.AddField(
            model_name='catalogue',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Collection'),
        ),
        migrations.AlterUniqueTogether(
            name='personcollectionrelation',
            unique_together={('person', 'collection')},
        ),
    ]
