# Generated by Django 2.0 on 2018-11-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20181101_1447'),
        ('items', '0010_item_index_in_lot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personitemrelation',
            unique_together={('person', 'item', 'role')},
        ),
    ]
