# Generated by Django 2.0 on 2018-11-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20181101_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='url',
            field=models.CharField(blank=True, max_length=1024, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of publication'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='year_tag',
            field=models.CharField(blank=True, max_length=128, verbose_name='Year of publication tag'),
        ),
    ]
