# Generated by Django 2.0 on 2018-02-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20180219_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookItemYearIntervalRelation',
            new_name='ItemYearIntervalRelation',
        ),
        migrations.RenameModel(
            old_name='PersonBookItemRelation',
            new_name='PersonItemRelation',
        ),
        migrations.RenameModel(
            old_name='PersonBookItemRelationType',
            new_name='PersonItemRelationType',
        ),
    ]
