# Generated by Django 2.0 on 2018-12-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20181217_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persons.Place'),
        ),
    ]
