# Generated by Django 2.0 on 2018-02-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20180219_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemyearintervalrelation',
            old_name='book_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='personitemrelation',
            old_name='book_item',
            new_name='item',
        ),
        migrations.AlterUniqueTogether(
            name='itemyearintervalrelation',
            unique_together={('item', 'year_interval')},
        ),
    ]
