# Generated by Django 2.0 on 2018-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20180219_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buyer',
            field=models.TextField(verbose_name='Buyer of an item'),
        ),
        migrations.AlterField(
            model_name='personitemrelationtype',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Type of person-item relation'),
        ),
    ]
