# Generated by Django 2.0 on 2018-02-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20180219_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonItemRelationType',
            new_name='PersonItemRelationRole',
        ),
    ]
