# Generated by Django 2.0 on 2019-02-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_historicalbookformat_historicalitem_historicalitemauthor_historicalitemitemtyperelation_historicalit'),
    ]

    operations = [
        migrations.RunSQL("CREATE INDEX items_item_manifestation_id_1090329b_fk_items_manifestation_uuid ON items_item (manifestation_id)"),
    ]
