# Generated by Django 2.0.13 on 2019-04-29 13:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0011_auto_20190429_1317'),
        ('items', '0018_create_item_manifestation_id_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manifestation',
            new_name='Edition',
        ),
        migrations.RenameModel(
            old_name='HistoricalManifestation',
            new_name='HistoricalEdition',
        ),
        migrations.AlterModelOptions(
            name='historicaledition',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical edition'},
        ),
        migrations.RenameField(
            model_name='historicalitem',
            old_name='manifestation',
            new_name='edition',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='manifestation',
            new_name='edition',
        ),
    ]
