# Generated by Django 2.0 on 2018-02-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_auto_20180219_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personitemrelation',
            old_name='type',
            new_name='role',
        ),
    ]
