# Generated by Django 2.0.13 on 2019-04-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_auto_20190429_1317'),
        ('items', '0019_auto_20190429_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpublisher',
            old_name='manifestation',
            new_name='edition',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='manifestation',
            new_name='edition',
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('publisher', 'edition')},
        ),
    ]
