# Generated by Django 2.0 on 2018-02-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_auto_20180219_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonCatalogueRelationType',
            new_name='PersonCatalogueRelationRole',
        ),
    ]
