# Generated by Django 2.0.13 on 2019-11-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_auto_20190429_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonitemrelation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='personitemrelation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
