# Generated by Django 2.0 on 2018-02-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20180219_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.Collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='catalogue_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.CatalogueEntry'),
        ),
    ]
