# Generated by Django 2.0.13 on 2019-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20191125_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='non_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='non_book',
            field=models.BooleanField(default=False),
        ),
    ]
