# Generated by Django 2.0 on 2018-03-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_auto_20180219_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogueEntry',
            new_name='Lot',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='catalogue_entry',
            new_name='lot',
        ),
    ]
