# Generated by Django 2.0.13 on 2019-11-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_auto_20191126_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='non_book',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='non_book',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
