    # Generated by Django 2.0.13 on 2020-12-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20191128_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RenameField(
            model_name='edition',
            old_name='year',
            new_name='year_start',
        ),
        migrations.RenameField(
            model_name='historicaledition',
            old_name='year',
            new_name='year_start',
        ),
        migrations.AddField(
            model_name='edition',
            name='year_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of publication - end'),
        ),
        migrations.AddField(
            model_name='historicaledition',
            name='year_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of publication - end'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='year_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of publication - start'),
        ),
        migrations.AlterField(
            model_name='historicaledition',
            name='year_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of publication - start'),
        ),
    ]
