# Generated by Django 2.0 on 2021-02-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0019_auto_20200604_0859'),
        ('items', '0024_edition_year_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='parisian_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogues.ParisianCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='parisian_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogues.ParisianCategory'),
        ),
    ]
