# Generated by Django 2.0 on 2018-03-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_auto_20180322_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleWork',
            new_name='Work',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title_work',
            new_name='work',
        ),
    ]
