# Generated by Django 2.0.13 on 2020-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_edition_year_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='catalogue_short_title',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='Catalogue - Short title'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='catalogue_year_of_publication',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Catalogue - Year of publication'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='lot_index_in_catalogue',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Lot - Index in catalogue'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='lot_lot_as_listed_in_catalogue',
            field=models.TextField(db_index=True, null=True, verbose_name='Lot - Full lot description, exactly as in the catalogue'),
        ),
        migrations.AddField(
            model_name='item',
            name='catalogue_short_title',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='Catalogue - Short title'),
        ),
        migrations.AddField(
            model_name='item',
            name='catalogue_year_of_publication',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Catalogue - Year of publication'),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_index_in_catalogue',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Lot - Index in catalogue'),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_lot_as_listed_in_catalogue',
            field=models.TextField(db_index=True, null=True, verbose_name='Lot - Full lot description, exactly as in the catalogue'),
        ),
    ]
