# Generated by Django 2.2.27 on 2022-04-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_auto_20210204_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalitem',
            old_name='collection',
            new_name='collection_TMP',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='collection',
            new_name='collection_TMP',
        ),
    ]
