# Generated by Django 2.0 on 2018-03-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_auto_20180323_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='viaf_id',
            field=models.CharField(max_length=32, null=True, verbose_name='VIAF ID of a work'),
        ),
    ]
