# Generated by Django 2.2.27 on 2022-04-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_auto_20220411_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalitem',
            old_name='collection_TMP',
            new_name='collection_tmp',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='collection_TMP',
            new_name='collection_tmp',
        ),
    ]
