# Generated by Django 2.2.27 on 2022-04-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0028_auto_20220414_1001'),
        ('items', '0027_auto_20220412_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='collection_tmp',
            new_name='catalogue',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='collection_tmp',
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='catalogue',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogues.Catalogue'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='number_of_volumes',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Number of volumes, as listed in the collection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='number_of_volumes',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Number of volumes, as listed in the collection'),
        ),
    ]
