# Generated by Django 2.0 on 2018-03-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_auto_20180329_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='text',
            new_name='name',
        ),
    ]
