# Generated by Django 2.2.28 on 2022-07-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_auto_20220414_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogues.Catalogue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogues.Lot'),
        ),
    ]
