# Generated by Django 2.0 on 2018-03-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_auto_20180329_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueHeldBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='The name of the library/institute')),
            ],
        ),
        migrations.RenameField(
            model_name='personcataloguerelation',
            old_name='type',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='place',
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='collectionyear',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Collection'),
        ),
        migrations.AddField(
            model_name='catalogueheldby',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Library'),
        ),
    ]
