# Generated by Django 2.2.28 on 2022-10-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_auto_20220711_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitemtype',
            name='non_book',
            field=models.BooleanField(default=True, verbose_name='Is non book type'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='non_book',
            field=models.BooleanField(default=True, verbose_name='Is non book type'),
        ),
    ]
