# Generated by Django 2.0 on 2018-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_auto_20180329_1458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemyearintervalrelation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itemyearintervalrelation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemyearintervalrelation',
            name='year_interval',
        ),
        migrations.AddField(
            model_name='publication',
            name='terminus_post_quem',
            field=models.BooleanField(default=False, verbose_name='Terminus post quem'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(verbose_name='Year of publication'),
        ),
        migrations.DeleteModel(
            name='ItemYearIntervalRelation',
        ),
        migrations.DeleteModel(
            name='YearInterval',
        ),
    ]
