# Generated by Django 2.0 on 2018-04-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0030_auto_20180405_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='type',
        ),
        migrations.RemoveField(
            model_name='catalogueheldby',
            name='catalogue',
        ),
        migrations.RemoveField(
            model_name='catalogueheldby',
            name='library',
        ),
        migrations.RemoveField(
            model_name='collectionyear',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='catalogue',
        ),
        migrations.RemoveField(
            model_name='personcataloguerelation',
            name='catalogue',
        ),
        migrations.RemoveField(
            model_name='personcataloguerelation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personcataloguerelation',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='personcollectionrelation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='personcollectionrelation',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='personcollectionrelation',
            name='person',
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.Collection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogues.Lot'),
        ),
        migrations.DeleteModel(
            name='Catalogue',
        ),
        migrations.DeleteModel(
            name='CatalogueHeldBy',
        ),
        migrations.DeleteModel(
            name='CatalogueType',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionYear',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.DeleteModel(
            name='PersonCatalogueRelation',
        ),
        migrations.DeleteModel(
            name='PersonCatalogueRelationRole',
        ),
        migrations.DeleteModel(
            name='PersonCollectionRelation',
        ),
    ]
