# Generated by Django 4.1.2 on 2022-11-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0030_auto_20221004_0910"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalbookformat",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical book format",
                "verbose_name_plural": "historical book formats",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaledition",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical edition",
                "verbose_name_plural": "historical editions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical item",
                "verbose_name_plural": "historical items",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalitemauthor",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical item author",
                "verbose_name_plural": "historical item authors",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalitemitemtyperelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical item item type relation",
                "verbose_name_plural": "historical item item type relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalitemlanguagerelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical item language relation",
                "verbose_name_plural": "historical item language relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalitemmaterialdetailsrelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical item material details relation",
                "verbose_name_plural": "historical item material details relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalitemtype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical item type",
                "verbose_name_plural": "historical item types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalitemworkrelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical item work relation",
                "verbose_name_plural": "historical item work relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallanguage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical language",
                "verbose_name_plural": "historical languages",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmaterialdetails",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical material details",
                "verbose_name_plural": "historical material detailss",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpersonitemrelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person item relation",
                "verbose_name_plural": "historical person item relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpersonitemrelationrole",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person item relation role",
                "verbose_name_plural": "historical person item relation roles",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpublisher",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical publisher",
                "verbose_name_plural": "historical publishers",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubject",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical subject",
                "verbose_name_plural": "historical subjects",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalwork",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical work",
                "verbose_name_plural": "historical works",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalworkauthor",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical work author",
                "verbose_name_plural": "historical work authors",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalworksubject",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical work subject",
                "verbose_name_plural": "historical work subjects",
            },
        ),
        migrations.AlterField(
            model_name="historicalbookformat",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaledition",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalitem",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalitemauthor",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalitemitemtyperelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalitemlanguagerelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalitemmaterialdetailsrelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalitemtype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalitemworkrelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicallanguage",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmaterialdetails",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpersonitemrelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpersonitemrelationrole",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpublisher",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsubject",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalwork",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalworkauthor",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalworksubject",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
