# Generated by Django 4.1.2 on 2022-11-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0031_alter_historicalbookformat_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalitem",
            name="uncountable_book_items",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="uncountable_book_items",
            field=models.BooleanField(default=False),
        ),
    ]
