# Generated by Django 2.0 on 2018-04-09 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20180329_1417'),
        ('items', '0031_auto_20180405_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAuthor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='persons.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBookFormatRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.BookFormat')),
            ],
        ),
        migrations.CreateModel(
            name='ItemItemTypeRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLanguageRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterialDetailsRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Name of the item type')),
            ],
        ),
        migrations.CreateModel(
            name='ItemWorkRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='binding_material_details',
        ),
        migrations.RemoveField(
            model_name='item',
            name='book_format',
        ),
        migrations.RemoveField(
            model_name='item',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='language',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sales_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='work',
        ),
        migrations.AddField(
            model_name='item',
            name='short_title',
            field=models.CharField(max_length=128, null=True, verbose_name='Short title'),
        ),
        migrations.AddField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RenameModel(
            old_name='BindingMaterialDetails',
            new_name='MaterialDetails',
        ),
        migrations.AddField(
            model_name='itemworkrelation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='items.Item'),
        ),
        migrations.AddField(
            model_name='itemworkrelation',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.Work'),
        ),
        migrations.AddField(
            model_name='itemmaterialdetailsrelation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
        migrations.AddField(
            model_name='itemmaterialdetailsrelation',
            name='material_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.MaterialDetails'),
        ),
        migrations.AddField(
            model_name='itemlanguagerelation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='items.Item'),
        ),
        migrations.AddField(
            model_name='itemlanguagerelation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.Language'),
        ),
        migrations.AddField(
            model_name='itemitemtyperelation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
        migrations.AddField(
            model_name='itemitemtyperelation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemType'),
        ),
        migrations.AddField(
            model_name='itembookformatrelation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_formats', to='items.Item'),
        ),
        migrations.AddField(
            model_name='itemauthor',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='items.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='itemworkrelation',
            unique_together={('item', 'work')},
        ),
        migrations.AlterUniqueTogether(
            name='itemmaterialdetailsrelation',
            unique_together={('item', 'material_details')},
        ),
        migrations.AlterUniqueTogether(
            name='itemlanguagerelation',
            unique_together={('item', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='itemitemtyperelation',
            unique_together={('item', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='itembookformatrelation',
            unique_together={('item', 'book_format')},
        ),
        migrations.AlterUniqueTogether(
            name='itemauthor',
            unique_together={('item', 'author')},
        ),
    ]
