# Generated by Django 4.2.1 on 2023-05-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0032_historicalitem_uncountable_book_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallanguage',
            name='language_code_2char',
            field=models.CharField(blank=True, db_index=True, help_text='Language code (2 characters long) of a written language. This also includes codes of the form zh-Hans, cf. IETF BCP 47', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='historicallanguage',
            name='language_code_3char',
            field=models.CharField(blank=True, db_index=True, help_text='ISO 639-3 language code (3 characters long) of a written language.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_code_2char',
            field=models.CharField(blank=True, help_text='Language code (2 characters long) of a written language. This also includes codes of the form zh-Hans, cf. IETF BCP 47', max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_code_3char',
            field=models.CharField(blank=True, help_text='ISO 639-3 language code (3 characters long) of a written language.', max_length=3, null=True, unique=True),
        ),
    ]
