# Generated by Django 2.0 on 2018-04-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0032_auto_20180409_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialdetails',
            old_name='text',
            new_name='description',
        ),
    ]
