# Generated by Django 4.2.1 on 2023-06-26 14:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_alter_historicalalternativepersonname_options_and_more'),
        ('items', '0033_alter_historicallanguage_language_code_2char_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPlace',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.edition')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.place')),
            ],
            options={
                'unique_together': {('edition', 'place')},
            },
        ),
    ]
