# Generated by Django 4.2.1 on 2023-06-26 14:25

from django.db import migrations


def copy_edition_place_to_publicationplace(apps, schema_editor):
    Edition = apps.get_model('items', 'Edition')
    PublicationPlace = apps.get_model('items', 'PublicationPlace')
    publication_places = [
        PublicationPlace(edition_id=edition.uuid, place_id=edition.place_id)
        for edition in Edition.objects.filter(place__isnull=False)
    ]
    PublicationPlace.objects.bulk_create(publication_places)


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_publicationplace'),
    ]

    operations = [
        migrations.RunPython(copy_edition_place_to_publicationplace),
    ]
