# Generated by Django 4.2.1 on 2023-07-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0038_item_items_item_dataset_05e420_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_collect_ee2d04_idx',
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='lot_index_in_collection',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='lot_lot_as_listed_in_collection',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_index_in_collection',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_lot_as_listed_in_collection',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['collection_year_of_publication', 'collection_short_title', 'lot_index_in_collection', 'index_in_lot', 'lot_lot_as_listed_in_collection'], name='items_item_collect_20c895_idx'),
        ),
    ]
