# Generated by Django 4.1.7 on 2023-11-13 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_alter_historicalalternativepersonname_options_and_more'),
        ('items', '0039_remove_item_items_item_collect_ee2d04_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.place'),
        ),
    ]
