# Generated by Django 4.2.26 on 2026-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0040_alter_edition_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='stated_publisher',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stated_publisher',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
