# Generated by Django 4.2.20 on 2025-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0040_alter_edition_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='earliest_edition_year',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['earliest_edition_year'], name='work_earliest_edition_year_idx'),
        ),
    ]
