# Generated by Django 2.0 on 2018-05-04 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simplemoderation.fields
import simplemoderation.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('C', simplemoderation.models.ModerationAction('C')), ('U', simplemoderation.models.ModerationAction('U')), ('D', simplemoderation.models.ModerationAction('D'))], default='C', editable=False, max_length=1)),
                ('data', simplemoderation.fields.SerializedObjectField(editable=False)),
                ('object_pk', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('state', models.CharField(choices=[('P', simplemoderation.models.ModerationState('P')), ('A', simplemoderation.models.ModerationState('A')), ('R', simplemoderation.models.ModerationState('R'))], default='P', max_length=1)),
                ('moderated_datetime', models.DateTimeField(null=True)),
                ('reason', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('editor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_objects', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_moderations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
