# Generated by Django 2.0 on 2018-05-02 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('C', 'create'), ('U', 'update'), ('D', 'delete')], default='C', max_length=1)),
                ('state', models.CharField(choices=[('P', 'pending'), ('A', 'approved'), ('R', 'rejected')], default='P', max_length=1)),
                ('data', models.TextField()),
                ('object_uuid', models.CharField(blank=True, default='', max_length=36)),
                ('datetime_state_change', models.DateTimeField(null=True)),
                ('reason', models.TextField(blank=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_edits', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_moderations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
