# Generated by Django 2.0 on 2018-10-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplemoderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simplemoderation.Moderation'),
        ),
    ]
