# Generated by Django 4.1.2 on 2022-11-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplemoderation", "0002_moderation_master"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
