# Generated by Django 2.0 on 2018-03-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpersonrelation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.PersonPersonRelationType'),
        ),
    ]
