# Generated by Django 2.0 on 2018-07-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['short_name']},
        ),
        migrations.AlterField(
            model_name='person',
            name='city_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_born', to='persons.Place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_died', to='persons.Place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='viaf_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='VIAF ID (https://viaf.org)'),
        ),
    ]
