# Generated by Django 2.0 on 2018-07-03 07:31

from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20180702_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=django_date_extensions.fields.ApproximateDateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=django_date_extensions.fields.ApproximateDateField(verbose_name='Date of death'),
        ),
    ]
