# Generated by Django 2.0 on 2018-07-16 10:20

from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20180703_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, verbose_name='Date of death'),
        ),
    ]
