# Generated by Django 2.0 on 2018-11-23 15:20

from django.db import migrations, models
import re

def correct_dates(apps, schema_editor):
    """
    The original data was from a ApproximateDateField which may be save as
    1999-00-00 or 1999-12-00. This function removes the -00 parts.
    :param apps: 
    :param schema_editor: 
    :return: 
    """
    Person = apps.get_model('persons', 'Person')
    for person in Person.objects.all():
        person.date_of_birth = re.sub('-00', '', person.date_of_birth)
        person.date_of_death = re.sub('-00', '', person.date_of_death)
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20181101_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=64, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.CharField(blank=True, max_length=64, verbose_name='Date of death'),
        ),
        migrations.RunPython(correct_dates),
    ]
