# Generated by Django 2.0.13 on 2019-03-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_historicalperson_historicalpersonpersonrelation_historicalpersonpersonrelationtype_historicalpersonp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplace',
            name='cerl_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='CERL ID of a place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='cerl_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='CERL ID of a place'),
        ),
    ]
