# Generated by Django 2.0.13 on 2019-04-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_auto_20190325_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
    ]
