# Generated by Django 2.0.13 on 2019-07-11 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0011_auto_20190429_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativePersonName',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=128, null=True, verbose_name='Short name')),
                ('surname', models.CharField(max_length=128, verbose_name='Surname')),
                ('first_names', models.CharField(max_length=512, verbose_name='First names')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_names', to='persons.Person')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAlternativePersonName',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('short_name', models.CharField(max_length=128, null=True, verbose_name='Short name')),
                ('surname', models.CharField(max_length=128, verbose_name='Surname')),
                ('first_names', models.CharField(max_length=512, verbose_name='First names')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persons.Person')),
            ],
            options={
                'verbose_name': 'historical alternative person name',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
