# Generated by Django 2.0.13 on 2019-09-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_alternativepersonname_historicalalternativepersonname'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
