# Generated by Django 2.0.13 on 2020-05-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_auto_20191126_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='publisher_cerl_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Publisher CERL ID'),
        ),
        migrations.AddField(
            model_name='person',
            name='publisher_cerl_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Publisher CERL ID'),
        ),
    ]
