# Generated by Django 2.2.27 on 2022-04-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0015_auto_20200504_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='religion',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='bibliography',
            field=models.TextField(blank=True, null=True, verbose_name='Bibliography'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown'), ('CORPRT', 'Corporate')], max_length=7, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bibliography',
            field=models.TextField(blank=True, null=True, verbose_name='Bibliography'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown'), ('CORPRT', 'Corporate')], max_length=7, verbose_name='Sex'),
        ),
    ]
