# Generated by Django 4.1.2 on 2022-11-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0016_auto_20220411_1225"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalalternativepersonname",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical alternative person name",
                "verbose_name_plural": "historical alternative person names",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcountry",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical country",
                "verbose_name_plural": "historical countries",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person",
                "verbose_name_plural": "historical persons",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpersonpersonrelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person person relation",
                "verbose_name_plural": "historical person person relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpersonpersonrelationtype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person person relation type",
                "verbose_name_plural": "historical person person relation types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpersonprofession",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person profession",
                "verbose_name_plural": "historical person professions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalplace",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical place",
                "verbose_name_plural": "historical places",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprofession",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical profession",
                "verbose_name_plural": "historical professions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreligion",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical religion",
                "verbose_name_plural": "historical religions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreligiousaffiliation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical religious affiliation",
                "verbose_name_plural": "historical religious affiliations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalresidence",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical residence",
                "verbose_name_plural": "historical residences",
            },
        ),
        migrations.AlterField(
            model_name="historicalalternativepersonname",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcountry",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpersonpersonrelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpersonpersonrelationtype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpersonprofession",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalplace",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprofession",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreligion",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreligiousaffiliation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalresidence",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
