# Generated by Django 4.1.7 on 2024-03-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_alter_historicalalternativepersonname_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='normalised_date_of_birth',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='normalised_date_of_death',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='normalised_date_of_birth',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='normalised_date_of_death',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
    ]
