# Generated by Django 4.2.15 on 2025-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0019_person_weight'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['weight'], name='weight_idx'),
        ),
    ]
