# Generated by Django 4.2.15 on 2025-02-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0020_person_weight_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='earliest_edition_year',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
