# Generated by Django 4.2.15 on 2025-02-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0021_person_earliest_edition_year'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['earliest_edition_year'], name='earliest_edition_year_idx'),
        ),
    ]
