# Generated by Django 4.2.26 on 2026-05-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0022_person_earliest_edition_year_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='birth_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Birth name'),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Birth name'),
        ),
    ]
