# Generated by Django 6.1 on 2026-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0023_historicalperson_birth_name_person_birth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalplace',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='person',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='place',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
